#!/usr/bin/env bash
set -euo pipefail

# Generate a Netlify _redirects file mapping each markdown filename (no extension)
# to its nested path (no extension).
#
# Usage:
#   ./generate_redirects.sh [root_dir] [output_file]
#
# Env vars:
#   STATUS_CODE   HTTP status to use (default: 301)
#   SLUGIFY       If "1", slugify the FROM path (lowercase, non-alnum -> "-") (default: 0)
#   WARN_DUPLICATES If "1", warn when multiple files share the same FROM (default: 1)
#
# Examples:
#   ./generate_redirects.sh content ./_redirects
#   SLUGIFY=1 STATUS_CODE=302 ./generate_redirects.sh

ROOT="${1:-.}"
OUT="${2:-_redirects}"
STATUS_CODE="${STATUS_CODE:-301}"
SLUGIFY="${SLUGIFY:-0}"
WARN_DUPLICATES="${WARN_DUPLICATES:-1}"

if [ ! -d "$ROOT" ]; then
  echo "Error: root directory \"$ROOT\" not found." >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

slugify() {
  # lowercase, replace non-alnum with '-', trim leading/trailing '-'
  # Note: uses POSIX tools
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

normalize_path() {
  # remove duplicate slashes, resolve "./" segments in a simple way
  # keep leading slash
  # input: path starting with "/"
  printf '%s' "$1" \
    | sed -E 's#//+#/#g; s#/\./#/#g; s#^/\.?/?#/#'
}

# Write header
{
  echo "# Auto-generated by generate_redirects.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "# Root: $ROOT"
  echo "# Status: $STATUS_CODE"
  echo "# Slugify FROM: $SLUGIFY"
} > "$OUT"

# Collect raw rules into tmp as tab-separated: FROM <tab> TO <tab> STATUS
# - FROM: "/<filename-no-ext>" (possibly slugified)
# - TO:   "/<relative/dir>/<filename-no-ext>" (index.md -> "/<relative/dir>" ; root index.md -> "/")
# Walk the tree safely with NUL delimiters
find "$ROOT" -type f \( -iname '*.md' -o -iname '*.mdx' \) -print0 \
| while IFS= read -r -d '' f; do
  rel="${f#"$ROOT"/}"
  base="$(basename "$f")"
  name="${base%.*}"      # filename without extension
  dir="$(dirname "$rel")"

  from_name="$name"
  if [ "$SLUGIFY" = "1" ]; then
    from_name="$(slugify "$from_name")"
  fi

  from="/$from_name"

  # Build TO path
  if [ "$name" = "index" ]; then
    if [ "$dir" = "." ]; then
      to="/"
    else
      to="/$dir"
    fi
  else
    if [ "$dir" = "." ]; then
      to="/$name"
    else
      to="/$dir/$name"
    fi
  fi

  from="$(normalize_path "$from")"
  to="$(normalize_path "$to")"

  # Skip empty FROM (possible if slugify produced empty)
  if [ -z "$from" ] || [ "$from" = "/" ]; then
    # Still allow "/index" if name was index and SLUGIFY removed it? We skip to be safe.
    continue
  fi

  # Write tab-separated for robust processing
  printf "%s\t%s\t%s\n" "$from" "$to" "$STATUS_CODE" >> "$tmp"
done

# Deduplicate by FROM (keep first); optionally warn about duplicates
awk -F '\t' -v OFS='\t' -v warn="$WARN_DUPLICATES" '
  {
    from=$1
    if (!(from in seen)) {
      seen[from]=NR
      lines[NR]=$0
      order[NR]=from
    } else if (warn) {
      dups[from]++
    }
  }
  END {
    for (i=1; i<=NR; i++) {
      if (i in lines) print lines[i]
    }
    if (warn) {
      for (k in dups) {
        printf "WARNING: duplicate source \"%s\". Only the first occurrence is kept.\n", k > "/dev/stderr"
      }
    }
  }
' "$tmp" >> "$OUT"

echo "Wrote $(wc -l < "$OUT") lines to $OUT"